name: Submit

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  publish:
    if: |
      github.event_name == 'pull_request' && github.event.pull_request.merged == true ||
      github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    steps:
      - uses: ryohidaka/wxt-submit@v1
        with:
          # For Chrome Extension
          chrome: true
          chrome-extension-id: "mlahdoiocbfocfhoodjfmkdadhkabpik"
          chrome-client-id: ${{ secrets.CHROME_CLIENT_ID }}
          chrome-client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          chrome-refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

          # For Firefox Addon
          firefox: true
          firefox-extension-id: "at-pizza-nico@hidaka.dev"
          firefox-jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          firefox-jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}

          # For Edge Extension
          edge: false
